In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("cleaned_sales_data.csv")

df['Date'] = pd.to_datetime(df['Date'])

df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,2010-02-05,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,2010-02-12,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,2010-02-19,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,2010-02-26,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,2010-03-05,1554806.68,0,46.50,2.625,211.350143,8.106

In [5]:
df['Year'] = df['Date'].dt.year

df['Month'] = df['Date'].dt.month

df['Week'] = df['Date'].dt.isocalendar().week

df['Quarter'] = df['Date'].dt.quarter

df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Year,Month,Week,Quarter
0,1,2010-02-05,1643690.90,0,42.31,2.572,211.096358,8.106,2010,2,5,1
1,1,2010-02-12,1641957.44,1,38.51,2.548,211.242170,8.106,2010,2,6,1
2,1,2010-02-19,1611968.17,0,39.93,2.514,211.289143,8.106,2010,2,7,1
3,1,2010-02-26,1409727.59,0,46.63,2.561,211.319643,8.106,2010,2,8,1
4,1,2010-03-05,1554806.68,0,46.50,2.625,211.350143,8.106,2010,3,9,1

In [7]:
df['lag_1'] = df.groupby('Store')['Weekly_Sales'].shift(1)

df['lag_4'] = df.groupby('Store')['Weekly_Sales'].shift(4)

df['lag_12'] = df.groupby('Store')['Weekly_Sales'].shift(12)

In [8]:
df[['Store','Date','Weekly_Sales','lag_1','lag_4','lag_12']].head(20)

    Store       Date  Weekly_Sales       lag_1       lag_4      lag_12
0       1 2010-02-05    1643690.90         NaN         NaN         NaN
1       1 2010-02-12    1641957.44  1643690.90         NaN         NaN
2       1 2010-02-19    1611968.17  1641957.44         NaN         NaN
3       1 2010-02-26    1409727.59  1611968.17         NaN         NaN
4       1 2010-03-05    1554806.68  1409727.59  1643690.90         NaN
5       1 2010-03-12    1439541.59  1554806.68  1641957.44         NaN
6       1 2010-03-19    1472515.79  1439541.59  1611968.17         NaN
7       1 2010-03-26    1404429.92  1472515.79  1409727.59         NaN
8       1 2010-04-02    1594968.28  1404429.92  1554806.68         NaN
9       1 2010-04-09    1545418.53  1594968.28  1439541.59         NaN
10      1 2010-04-16    1466058.28  1545418.53  1472515.79         NaN
11      1 2010-04-23    1391256.12  1466058.28  1404429.92         NaN
12      1 2010-04-30    1425100.71  1391256.12  1594968.28  1643690.90
13      1 2010-05-07    1603955.12  1425100.71  1545418.53  1641957.44
14      1 2010-05-14    1494251.50  1603955.12  1466058.28  1611968.17
15      1 2010-05-21    1399662.07  1494251.50  1391256.12  1409727.59
16      1 2010-05-28    1432069.95  1399662.07  1425100.71  1554806.68
17      1 2010-06-04    1615524.71  1432069.95  1603955.12  1439541.59
18      1 2010-06-11    1542561.09  1615524.71  1494251.50  1472515.79
19      1 2010-06-18    1503284.06  1542561.09  1399662.07  1404429.92

In [10]:
df['rolling_mean_4'] = (
    df.groupby('Store')['Weekly_Sales']
      .transform(lambda x: x.shift(1).rolling(4).mean())
)

df['rolling_mean_12'] = (
    df.groupby('Store')['Weekly_Sales']
      .transform(lambda x: x.shift(1).rolling(12).mean())
)

df['rolling_std_4'] = (
    df.groupby('Store')['Weekly_Sales']
      .transform(lambda x: x.shift(1).rolling(4).std())
)

In [11]:
df.dropna(inplace=True)

df.to_csv("feature_engineered_data.csv", index=False)

In [12]:
df['Year'] = df['Date'].dt.year